spring.application.name=backend-api

# API keys stored locally in application-secrets.properties file
spring.profiles.include=secrets

# Caching config
spring.cache.cache-names=articles
spring.cache.caffeine.spec=initialCapacity=30,maximumSize=100,expireAfterWrite=15m

